# Generated by Django 5.0.4 on 2024-04-20 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("galeria", "0003_fotografia_publicada"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fotografia",
            name="descricao",
            field=models.CharField(max_length=100),
        ),
    ]
